// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: http_request_proto.proto
// Protobuf C++ Version: 5.29.3

#include "http_request_proto.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr HttpProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reply_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR HttpProto::HttpProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HttpProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HttpProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HttpProtoDefaultTypeInternal() {}
  union {
    HttpProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HttpProtoDefaultTypeInternal _HttpProto_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_http_5frequest_5fproto_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_http_5frequest_5fproto_2eproto = nullptr;
const ::uint32_t
    TableStruct_http_5frequest_5fproto_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::HttpProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::HttpProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::HttpProto, _impl_.request_),
        PROTOBUF_FIELD_OFFSET(::HttpProto, _impl_.reply_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::HttpProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_HttpProto_default_instance_._instance,
};
const char descriptor_table_protodef_http_5frequest_5fproto_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030http_request_proto.proto\"+\n\tHttpProto\022"
    "\017\n\007request\030\001 \002(\t\022\r\n\005reply\030\002 \002(\t"
};
static ::absl::once_flag descriptor_table_http_5frequest_5fproto_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_http_5frequest_5fproto_2eproto = {
    false,
    false,
    71,
    descriptor_table_protodef_http_5frequest_5fproto_2eproto,
    "http_request_proto.proto",
    &descriptor_table_http_5frequest_5fproto_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_http_5frequest_5fproto_2eproto::offsets,
    file_level_enum_descriptors_http_5frequest_5fproto_2eproto,
    file_level_service_descriptors_http_5frequest_5fproto_2eproto,
};
// ===================================================================

class HttpProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<HttpProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HttpProto, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

HttpProto::HttpProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:HttpProto)
}
inline PROTOBUF_NDEBUG_INLINE HttpProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::HttpProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        request_(arena, from.request_),
        reply_(arena, from.reply_) {}

HttpProto::HttpProto(
    ::google::protobuf::Arena* arena,
    const HttpProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HttpProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:HttpProto)
}
inline PROTOBUF_NDEBUG_INLINE HttpProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        request_(arena),
        reply_(arena) {}

inline void HttpProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HttpProto::~HttpProto() {
  // @@protoc_insertion_point(destructor:HttpProto)
  SharedDtor(*this);
}
inline void HttpProto::SharedDtor(MessageLite& self) {
  HttpProto& this_ = static_cast<HttpProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.request_.Destroy();
  this_._impl_.reply_.Destroy();
  this_._impl_.~Impl_();
}

inline void* HttpProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) HttpProto(arena);
}
constexpr auto HttpProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HttpProto),
                                            alignof(HttpProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull HttpProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_HttpProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        HttpProto::IsInitializedImpl,
        &HttpProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<HttpProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &HttpProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<HttpProto>(), &HttpProto::ByteSizeLong,
            &HttpProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(HttpProto, _impl_._cached_size_),
        false,
    },
    &HttpProto::kDescriptorMethods,
    &descriptor_table_http_5frequest_5fproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* HttpProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> HttpProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HttpProto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::HttpProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required string reply = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(HttpProto, _impl_.reply_)}},
    // required string request = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HttpProto, _impl_.request_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string request = 1;
    {PROTOBUF_FIELD_OFFSET(HttpProto, _impl_.request_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string reply = 2;
    {PROTOBUF_FIELD_OFFSET(HttpProto, _impl_.reply_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\11\7\5\0\0\0\0\0"
    "HttpProto"
    "request"
    "reply"
  }},
};

PROTOBUF_NOINLINE void HttpProto::Clear() {
// @@protoc_insertion_point(message_clear_start:HttpProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.request_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.reply_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* HttpProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const HttpProto& this_ = static_cast<const HttpProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* HttpProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const HttpProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:HttpProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required string request = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_request();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "HttpProto.request");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // required string reply = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_reply();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "HttpProto.reply");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:HttpProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t HttpProto::ByteSizeLong(const MessageLite& base) {
          const HttpProto& this_ = static_cast<const HttpProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t HttpProto::ByteSizeLong() const {
          const HttpProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:HttpProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // required string request = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_request());
            }
            // required string reply = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_reply());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void HttpProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HttpProto*>(&to_msg);
  auto& from = static_cast<const HttpProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HttpProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_request(from._internal_request());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_reply(from._internal_reply());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HttpProto::CopyFrom(const HttpProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HttpProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HttpProto::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const HttpProto&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void HttpProto::InternalSwap(HttpProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.request_, &other->_impl_.request_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reply_, &other->_impl_.reply_, arena);
}

::google::protobuf::Metadata HttpProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_http_5frequest_5fproto_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
